'use strict';

const { Gateway, Wallets } = require('fabric-network');
const fs = require('fs');
const path = require('path');

/**
 * Thin wrapper around the fabric-network SDK. Opens a gateway connection,
 * gets the documentanchor contract, and exposes submit/evaluate helpers so
 * routes don't need to know anything about Fabric internals.
 */
class FabricService {
  constructor() {
    this.gateway = null;
    this.contract = null;
  }

  async connect() {
    if (this.contract) return this.contract; // already connected

    const connectionProfilePath = process.env.FABRIC_CONNECTION_PROFILE;
    const walletPath = process.env.FABRIC_WALLET_PATH;
    const identity = process.env.FABRIC_IDENTITY || 'appUser';
    const channelName = process.env.FABRIC_CHANNEL_NAME || 'sentinelchannel';
    const chaincodeName = process.env.FABRIC_CHAINCODE_NAME || 'documentanchor';

    if (!connectionProfilePath || !fs.existsSync(connectionProfilePath)) {
      throw new Error(
        `Connection profile not found at ${connectionProfilePath}. ` +
        `Copy the connection profile generated by fabric-samples/test-network ` +
        `(under organizations/peerOrganizations/.../connection-*.json) into config/.`
      );
    }

    const connectionProfile = JSON.parse(fs.readFileSync(connectionProfilePath, 'utf8'));
    const wallet = await Wallets.newFileSystemWallet(walletPath);

    const identityExists = await wallet.get(identity);
    if (!identityExists) {
      throw new Error(
        `Identity "${identity}" not found in wallet at ${walletPath}. ` +
        `Enroll it first using the fabric-samples enrollAdmin/registerUser scripts.`
      );
    }

    this.gateway = new Gateway();
    await this.gateway.connect(connectionProfile, {
      wallet,
      identity,
      discovery: {
        enabled: true,
        // true when the API runs directly on the host (matches test-network's
        // localhost-advertised peers). Must be false when this service runs
        // inside a Docker container joined to Fabric's network — see
        // docker-compose.yml and the README's "Running in Docker" note.
        asLocalhost: process.env.FABRIC_DISCOVERY_AS_LOCALHOST !== 'false',
      },
    });

    const network = await this.gateway.getNetwork(channelName);
    this.contract = network.getContract(chaincodeName);

    return this.contract;
  }

  async anchor(documentId, versionId, hash, uploaderId) {
    const contract = await this.connect();
    const timestamp = new Date().toISOString();

    const resultBuffer = await contract.submitTransaction(
      'anchorDocumentHash',
      documentId,
      versionId,
      hash,
      uploaderId,
      timestamp
    );

    const result = JSON.parse(resultBuffer.toString());
    return {
      txId: result.txId,
      anchoredAt: result.anchoredAt,
    };
  }

  async getAnchor(documentId, versionId) {
    const contract = await this.connect();
    const resultBuffer = await contract.evaluateTransaction(
      'verifyDocumentHash',
      documentId,
      versionId
    );
    return JSON.parse(resultBuffer.toString());
  }

  async getAuditHistory(documentId) {
    const contract = await this.connect();
    const resultBuffer = await contract.evaluateTransaction('getAuditHistory', documentId);
    return JSON.parse(resultBuffer.toString());
  }

  async disconnect() {
    if (this.gateway) {
      this.gateway.disconnect();
      this.gateway = null;
      this.contract = null;
    }
  }
}

module.exports = new FabricService();
