'use strict';

const forge = require('node-forge');
const fs = require('fs');
const path = require('path');

/**
 * PKI-based signing service.
 *
 * PROTOTYPE NOTE: uses a self-signed CA generated by scripts/generate-ca.js.
 * Call this out explicitly in the report/pitch — a production deployment
 * would integrate with India's DSC/eSign infrastructure instead of a
 * self-signed root.
 */
class SignatureService {
  constructor() {
    this.caCert = null;
    this.caKey = null;
    this.storePath = process.env.SIGNATURE_STORE_PATH || './ca/signatures-store.json';
  }

  _loadStore() {
    if (!fs.existsSync(this.storePath)) return {};
    return JSON.parse(fs.readFileSync(this.storePath, 'utf8'));
  }

  _saveStore(store) {
    const dir = path.dirname(this.storePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(this.storePath, JSON.stringify(store, null, 2));
  }

  _loadCA() {
    if (this.caCert && this.caKey) return;

    const caCertPath = process.env.CA_CERT_PATH || './ca/ca-cert.pem';
    const caKeyPath = process.env.CA_KEY_PATH || './ca/ca-key.pem';

    if (!fs.existsSync(caCertPath) || !fs.existsSync(caKeyPath)) {
      throw new Error(
        `CA cert/key not found at ${caCertPath} / ${caKeyPath}. ` +
        `Run "npm run generate-ca" first.`
      );
    }

    this.caCert = forge.pki.certificateFromPem(fs.readFileSync(caCertPath, 'utf8'));
    this.caKey = forge.pki.privateKeyFromPem(fs.readFileSync(caKeyPath, 'utf8'));
  }

  /**
   * Issues a user certificate signed by the prototype CA, if one doesn't
   * already exist for this userId. In a real deployment this step would be
   * replaced entirely by DSC/eSign issuance.
   */
  _getOrCreateUserCert(userId) {
    const certStorePath = process.env.CERT_STORE_PATH || './ca/issued';
    if (!fs.existsSync(certStorePath)) fs.mkdirSync(certStorePath, { recursive: true });

    const certPath = path.join(certStorePath, `${userId}-cert.pem`);
    const keyPath = path.join(certStorePath, `${userId}-key.pem`);

    if (fs.existsSync(certPath) && fs.existsSync(keyPath)) {
      return {
        cert: forge.pki.certificateFromPem(fs.readFileSync(certPath, 'utf8')),
        privateKey: forge.pki.privateKeyFromPem(fs.readFileSync(keyPath, 'utf8')),
      };
    }

    this._loadCA();

    const keys = forge.pki.rsa.generateKeyPair(2048);
    const cert = forge.pki.createCertificate();
    cert.publicKey = keys.publicKey;
    cert.serialNumber = Date.now().toString();
    cert.validity.notBefore = new Date();
    cert.validity.notAfter = new Date();
    cert.validity.notAfter.setFullYear(cert.validity.notBefore.getFullYear() + 1);

    const attrs = [{ name: 'commonName', value: userId }];
    cert.setSubject(attrs);
    cert.setIssuer(this.caCert.subject.attributes);
    cert.sign(this.caKey, forge.md.sha256.create());

    fs.writeFileSync(certPath, forge.pki.certificateToPem(cert));
    fs.writeFileSync(keyPath, forge.pki.privateKeyToPem(keys.privateKey));

    return { cert, privateKey: keys.privateKey };
  }

  /**
   * Signs a documentVersionId on behalf of userId. In practice you'd sign a
   * hash of the actual document content plus metadata rather than the bare
   * ID — this keeps the prototype simple while showing the full PKI flow.
   */
  sign(documentVersionId, userId) {
    const { privateKey } = this._getOrCreateUserCert(userId);

    const md = forge.md.sha256.create();
    md.update(documentVersionId, 'utf8');
    const signatureBytes = privateKey.sign(md);
    const signatureValue = forge.util.encode64(signatureBytes);
    const signedAt = new Date().toISOString();

    // Persist so /signatures/:documentVersionId/verify can look this up
    // without the caller having to resend the signature value.
    const store = this._loadStore();
    store[documentVersionId] = { signatureValue, signedBy: userId, signedAt };
    this._saveStore(store);

    return { signatureValue, signedAt, signedBy: userId };
  }

  /**
   * Verifies the signature on file for documentVersionId against the stored
   * cert for whoever signed it. Returns isValid + who/when for the
   * /signatures/:id/verify route.
   */
  verify(documentVersionId) {
    const store = this._loadStore();
    const record = store[documentVersionId];

    if (!record) {
      return { isValid: false, reason: `No signature on file for ${documentVersionId}` };
    }

    const { signatureValue, signedBy, signedAt } = record;
    const certStorePath = process.env.CERT_STORE_PATH || './ca/issued';
    const certPath = path.join(certStorePath, `${signedBy}-cert.pem`);

    if (!fs.existsSync(certPath)) {
      return { isValid: false, reason: `No certificate on file for ${signedBy}` };
    }

    const cert = forge.pki.certificateFromPem(fs.readFileSync(certPath, 'utf8'));
    const md = forge.md.sha256.create();
    md.update(documentVersionId, 'utf8');

    const signatureBytes = forge.util.decode64(signatureValue);
    const isValid = cert.publicKey.verify(md.digest().bytes(), signatureBytes);

    return { isValid, signedBy, signedAt };
  }
}

module.exports = new SignatureService();
